# Generated by Django 3.1 on 2021-04-29 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'Astana'), (2, 'Almaty'), (3, 'Akmola Region'), (4, 'Aktobe Region'), (5, 'Almaty Region'), (6, 'Atyrou Region'), (7, 'West Kazakhstan Region'), (8, 'Zhambil Region'), (9, 'Karagandy Region'), (10, 'Kostanai Region'), (11, 'Kyzylorda Region'), (12, 'Mangistau Region'), (13, 'South Kazakhstan Region'), (14, 'Pavlodar Region'), (15, 'North Kazakhstan Region'), (16, 'East Kazakhstan Region')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 29, 14, 39, 34, 275813))),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['date_created'],
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('baseaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baseaddress')),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ShippingAddress',
                'verbose_name_plural': 'ShippingAddresses',
            },
            bases=('api.baseaddress',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=-1)),
                ('location', models.PositiveSmallIntegerField(choices=[(1, 'Astana'), (2, 'Almaty'), (3, 'Akmola Region'), (4, 'Aktobe Region'), (5, 'Almaty Region'), (6, 'Atyrou Region'), (7, 'West Kazakhstan Region'), (8, 'Zhambil Region'), (9, 'Karagandy Region'), (10, 'Kostanai Region'), (11, 'Kyzylorda Region'), (12, 'Mangistau Region'), (13, 'South Kazakhstan Region'), (14, 'Pavlodar Region'), (15, 'North Kazakhstan Region'), (16, 'East Kazakhstan Region')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='api.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
