# Generated by Django 3.1 on 2021-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210514_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaddress',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Astana'), (2, 'Almaty'), (3, 'Akmola Region'), (4, 'Aktobe Region'), (5, 'Almaty Region'), (6, 'Atyrou Region'), (7, 'West Kazakhstan Region'), (8, 'Zhambil Region'), (9, 'Karagandy Region'), (10, 'Kostanai Region'), (11, 'Kyzylorda Region'), (12, 'Mangistau Region'), (13, 'South Kazakhstan Region'), (14, 'Pavlodar Region'), (15, 'North Kazakhstan Region'), (16, 'East Kazakhstan Region')], max_length=50, unique=True),
        ),
    ]
