# Generated by Django 3.1 on 2021-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210430_1730'),
        ('auth_', '0002_auto_20210429_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
    ]
