# Generated by Django 3.1 on 2021-04-30 13:59

import auth_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=auth_.models.wrapper),
        ),
    ]
