# Generated by Django 3.1 on 2021-05-05 14:16

import auth_.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0007_auto_20210505_2015'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('users', auth_.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
